.TH "JSHEETS" "" "May 2015" "" ""
.SH "NAME"
\fBjsheets\fR
.SH NAME
.P
jsheets \- A simple CSS preprocessor that interprets JavaScript
.SH SYNOPSYS
.P
\fBjsheets \fIfile\fR\fR
.SH DESCRIPTION
.P
Jsheets is a CSS preprocessor that executes JavaScript\. It also replaces function calls and variables inside CSS\. A simple approach to CSS preprocessing\.
.SH SYNTAX
.SS The \fB$\fR Object
.P
Inside CSS the whole \fB$\fR object is availible to you\. That's it\.
.P
.RS 2
.nf
div {
  background: $\.someColor;
}
.fi
.RE
.SS \fBinclude\fR
.P
With \fBinclude\fR you can import files to a jsheet\. Its usage is straight forward:
.P
.RS 2
.nf
include 'somefile\.jsheet'
.fi
.RE
.SS \fBcss()\fR
.P
With the \fBcss\fR function you can output css\. So you can do:
.P
.RS 2
.nf
css('div {display: block}')
.fi
.RE
.SS Variable Scope
.P
Every file has it's own local scope\. But the \fB$\fR\-object is global\.
.SS helpers
.P
Because underscore is used in the project, I thought i'd pass it to the jsheets\. There are also some helpers provided inside the \fB$\fR object\.
.SS $
.P
\fB$\.$\fR is a function that executes and returns what is passed to it\. This can be usefull for math or sometimes you can use it to use variables in weird places\. Example:
.P
.RS 2
.nf
div {
  width: $\.$(100 * 30)px
  /* WON'T WORK */
  width: $\.someWithem
  /* WILL WORK */
  width: $\.$($\.someWith)em
}
.fi
.RE
.SS extend
.P
With \fBextend\fR you can reuse css attributes\. It has two methods: \fBadd\fR and \fBthat\fR\|\. With add you create save a bunch of attributes under a name\.
.P
.RS 2
.nf
$\.extend\.add('roundbutton', '\\
  display: block;'
)
.fi
.RE
.P
Then with \fBextend\.that\fR you can then reuse those attributes\.
.P
.RS 2
.nf
$\.extend\.that('roundbutton', '\.dialogue__button')
$\.extend\.that('roundbutton', '\.escape__button')
.fi
.RE
.P
What is special about this function, is that it renders only one CSS block per \fBextend\.add\fR\|\. So the above renders to:
.P
.RS 2
.nf
roundbutton, \.dialogue__button, \.escape__button {  display: block; }
.fi
.RE
.SS onDone
.P
On done is an array you can push functions to that get executed at the and of parsing a file\. The return value of a onDone hook will get printed as CSS\.
.P
You cannot use braces inside of a call to \fB$\.$\fR\|\. That's because the \fB$\fR variables and functions are replaced using a mediocar RegEx\.
.SH ROADMAP
.P
I'm pretty ok with the package as it stands right now\. But there are a lot of things I plan to implement\.
.RS 0
.IP \(bu 2
Globbing
.IP \(bu 2
Integration
.RS 0
.IP \(bu 2
express
.IP \(bu 2
meteor

.RE
.IP \(bu 2
Highlighting
.RS 0
.IP \(bu 2
SublimeText

.RE

.RE

